# overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - includeSelectors: true
    pairs:
      env: production
      namePrefix: prod

images:
  - name: fumnanya92/kustomizeadv-nginx
    newName: fumnanya92/kustomizeadv-nginx
    newTag: latest
