name: Deploy with kustomize
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1
      - name: Apply Kustomize (skip validation)
        run: kubectl apply -k ./overlays/prod/ --validate=false
      # - name: Deploy to Kubernetes
      #   run: |
      #     kubectl apply -k ./overlays/prod/
      - name: Dry-run Kustomize apply
        run: kubectl apply -k ./overlays/prod/ --dry-run=client




      